# Generated by Django 4.2.27 on 2025-12-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=20)),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("summary", models.TextField(help_text="2-3 line summary of the call")),
                (
                    "lead_quality",
                    models.CharField(
                        choices=[("HOT", "Hot"), ("WARM", "Warm"), ("COLD", "Cold")],
                        default="WARM",
                        max_length=20,
                    ),
                ),
                (
                    "purchase_likelihood",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "call_outcome",
                    models.CharField(
                        choices=[
                            ("BOOKING_CONFIRMED", "Booking Confirmed"),
                            ("INTERESTED", "Interested"),
                            ("CALLBACK_REQUESTED", "Callback Requested"),
                            ("TRANSFERRED", "Transferred to Agent"),
                            ("DROPPED", "Dropped"),
                            ("NOT_INTERESTED", "Not Interested"),
                        ],
                        default="DROPPED",
                        max_length=30,
                    ),
                ),
                (
                    "cars_discussed",
                    models.JSONField(
                        default=list, help_text="List of car slugs discussed"
                    ),
                ),
                (
                    "preferred_car",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "preferred_color",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "budget_range",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "objections",
                    models.JSONField(
                        default=list, help_text="List of objections raised"
                    ),
                ),
                ("call_duration_seconds", models.IntegerField(default=0)),
                ("is_latest", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number", "-created_at"],
                        name="api_callsum_phone_n_d010a9_idx",
                    ),
                    models.Index(
                        fields=["phone_number", "is_latest"],
                        name="api_callsum_phone_n_310dd6_idx",
                    ),
                ],
            },
        ),
    ]
