# Generated by Django 4.2.27 on 2026-01-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsummary',
            name='cars_discussed',
        ),
        migrations.RemoveField(
            model_name='callsummary',
            name='preferred_car',
        ),
        migrations.AddField(
            model_name='callsummary',
            name='items_discussed',
            field=models.JSONField(default=list, help_text='List of items/products discussed'),
        ),
        migrations.AddField(
            model_name='callsummary',
            name='preferred_item',
            field=models.CharField(blank=True, help_text='The main item/product customer showed interest in', max_length=100, null=True),
        ),
    ]
