# Generated by Django 4.2.27 on 2026-01-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_callsummary_cars_discussed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rolling_summary', models.TextField(help_text='Exactly 3 lines - rolling summary of all interactions')),
                ('keywords', models.JSONField(default=list, help_text='Cumulative list of important keywords/phrases (max 50)')),
                ('total_calls', models.IntegerField(default=0)),
                ('last_call_id', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CallSummaryShort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('summary', models.TextField(help_text='Exactly 3 lines summarizing this call')),
                ('keywords', models.JSONField(default=list, help_text='Max 5 important keywords/phrases from this call')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', '-created_at'], name='api_callsum_phone_n_f46fc9_idx')],
            },
        ),
    ]
